//___________________Testing Object
// jlb removed test objects
// var evts = {
//     "event": [{ "watching_count": null, "olson_path": "America/New_York", "calendar_count": null, "comment_count": null, "region_abbr": "NC", "postal_code": "28202", "going_count": null, "all_day": "0", "latitude": "35.2250606", "groups": null, "url": "http://charlotte.eventful.com/events/chris-brown-50-cent-ot-genasis-fabolous-/E0-001-100571011-9?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "E0-001-100571011-9", "privacy": "1", "city_name": "Charlotte", "link_count": null, "longitude": "-80.8393335", "country_name": "United States", "country_abbr": "USA", "region_name": "North Carolina", "start_time": "2017-04-04 19:30:00", "tz_id": null, "description": null, "modified": "2017-02-23 09:50:12", "venue_display": "1", "tz_country": null, "performers": { "performer": [{ "creator": "Zombalabelgroup", "linker": "sara_sd", "name": "Chris Brown", "url": "http://concerts.eventful.com/Chris-Brown?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000002252-4", "short_bio": "R&B" }, { "creator": "interscoperecords", "linker": "evdb", "name": "50 Cent", "url": "http://concerts.eventful.com/50-Cent?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000008111-0", "short_bio": "Rap/Hip Hop" }, { "creator": "drew1733", "linker": "evdb", "name": "Fabolous", "url": "http://concerts.eventful.com/Fabolous?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000006441-4", "short_bio": "Hip Hop/Rap" }, { "creator": "TaylorRea", "linker": "evdb", "name": "O.T. Genasis", "url": "http://concerts.eventful.com/performers/ot-genasis-/P0-001-014203586-2?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-014203586-2", "short_bio": "Rapper" }] }, "title": "Chris Brown, 50 Cent, OT Genasis & Fabolous", "venue_address": "333 East Trade Street", "geocode_type": "EVDB Geocoder", "tz_olson_path": null, "recur_string": null, "calendars": null, "owner": "sara_sd", "going": null, "country_abbr2": "US", "categories": { "category": [{ "name": "Concerts &amp; Tour Dates", "id": "music" }] }, "image": { "small": { "width": "48", "url": "http://s1.evcdn.com/images/small/I0-001/021/529/792-2.jpeg_/chris-brown-92.jpeg", "height": "48" }, "width": "48", "caption": null, "medium": { "width": "128", "url": "http://s1.evcdn.com/images/medium/I0-001/021/529/792-2.jpeg_/chris-brown-92.jpeg", "height": "128" }, "url": "http://s1.evcdn.com/images/small/I0-001/021/529/792-2.jpeg_/chris-brown-92.jpeg", "thumb": { "width": "48", "url": "http://s1.evcdn.com/images/thumb/I0-001/021/529/792-2.jpeg_/chris-brown-92.jpeg", "height": "48" }, "height": "48" }, "created": "2017-02-21 13:23:11", "venue_id": "V0-001-001286706-3", "tz_city": null, "stop_time": null, "venue_name": "Spectrum Center (formerly Time Warner Cable Arena)", "venue_url": "http://charlotte.eventful.com/venues/spectrum-center-formerly-time-warner-cable-a-/V0-001-001286706-3?utm_source=apis&utm_medium=apim&utm_campaign=apic" },

//         { "watching_count": null, "olson_path": "America/New_York", "calendar_count": null, "comment_count": null, "region_abbr": "NC", "postal_code": "28205", "going_count": null, "all_day": "0", "latitude": "35.1960650", "groups": null, "url": "http://charlotte.eventful.com/events/leela-james-daley-/E0-001-100955021-4?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "E0-001-100955021-4", "privacy": "1", "city_name": "Charlotte", "link_count": null, "longitude": "-80.7893190", "country_name": "United States", "country_abbr": "USA", "region_name": "North Carolina", "start_time": "2017-04-06 20:00:00", "tz_id": null, "description": null, "modified": "2017-03-24 03:47:31", "venue_display": "1", "tz_country": null, "performers": { "performer": { "creator": "peelbacks", "linker": "evdb", "name": "Leela James", "url": "http://concerts.eventful.com/Leela-James?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000095572-7", "short_bio": "Soul / Blues / R&B" } }, "title": "Leela James & Daley", "venue_address": "4205 Monroe Road", "geocode_type": "EVDB Geocoder", "tz_olson_path": null, "recur_string": null, "calendars": null, "owner": "evdb", "going": null, "country_abbr2": "US", "categories": { "category": [{ "name": "Concerts &amp; Tour Dates", "id": "music" }] }, "image": { "small": { "width": "48", "url": "http://s2.evcdn.com/images/small/I0-001/004/141/961-7.jpeg_/leela-james-61.jpeg", "height": "48" }, "width": "48", "caption": null, "medium": { "width": "128", "url": "http://s2.evcdn.com/images/medium/I0-001/004/141/961-7.jpeg_/leela-james-61.jpeg", "height": "128" }, "url": "http://s2.evcdn.com/images/small/I0-001/004/141/961-7.jpeg_/leela-james-61.jpeg", "thumb": { "width": "48", "url": "http://s2.evcdn.com/images/thumb/I0-001/004/141/961-7.jpeg_/leela-james-61.jpeg", "height": "48" }, "height": "48" }, "created": "2017-03-06 11:35:37", "venue_id": "V0-001-001378336-0", "tz_city": null, "stop_time": null, "venue_name": "Charlotte's Underground", "venue_url": "http://charlotte.eventful.com/venues/charlottes-underground-/V0-001-001378336-0?utm_source=apis&utm_medium=apim&utm_campaign=apic" },

//         { "watching_count": null, "olson_path": "America/New_York", "calendar_count": null, "comment_count": null, "region_abbr": "NC", "postal_code": "28206", "going_count": null, "all_day": "0", "latitude": "35.23985927304726", "groups": null, "url": "http://charlotte.eventful.com/events/marsha-ambrosius-eric-benet-/E0-001-100256541-1?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "E0-001-100256541-1", "privacy": "1", "city_name": "Charlotte", "link_count": null, "longitude": "-80.84523939814756", "country_name": "United States", "country_abbr": "USA", "region_name": "North Carolina", "start_time": "2017-04-09 20:00:00", "tz_id": null, "description": null, "modified": "2017-03-24 12:36:01", "venue_display": "1", "tz_country": null, "performers": { "performer": [{ "creator": "evdb", "linker": "evdb", "name": "Marsha Ambrosius", "url": "http://concerts.eventful.com/Marsha-Ambrosius?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000204091-3", "short_bio": "songwriter and revered platinum-selling artist" }, { "creator": "Sassexy", "linker": "evdb", "name": "Eric Benet", "url": "http://concerts.eventful.com/Eric-Benet?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000036645-5", "short_bio": "R&B Singer" }] }, "title": "Marsha Ambrosius & Eric Benet", "venue_address": "820 Hamilton St,", "geocode_type": "EVDB Geocoder", "tz_olson_path": null, "recur_string": null, "calendars": null, "owner": "evdb", "going": null, "country_abbr2": "US", "categories": { "category": [{ "name": "Concerts &amp; Tour Dates", "id": "music" }] }, "image": { "small": { "width": "48", "url": "http://s2.evcdn.com/images/small/I0-001/004/071/557-8.jpeg_/marsha-ambrosius-57.jpeg", "height": "48" }, "width": "48", "caption": null, "medium": { "width": "128", "url": "http://s2.evcdn.com/images/medium/I0-001/004/071/557-8.jpeg_/marsha-ambrosius-57.jpeg", "height": "128" }, "url": "http://s2.evcdn.com/images/small/I0-001/004/071/557-8.jpeg_/marsha-ambrosius-57.jpeg", "thumb": { "width": "48", "url": "http://s2.evcdn.com/images/thumb/I0-001/004/071/557-8.jpeg_/marsha-ambrosius-57.jpeg", "height": "48" }, "height": "48" }, "created": "2017-02-09 15:43:35", "venue_id": "V0-001-004658846-2", "tz_city": null, "stop_time": null, "venue_name": "The Fillmore Charlotte", "venue_url": "http://charlotte.eventful.com/venues/the-fillmore-charlotte-/V0-001-004658846-2?utm_source=apis&utm_medium=apim&utm_campaign=apic" },

//         { "watching_count": null, "olson_path": "America/New_York", "calendar_count": null, "comment_count": null, "region_abbr": "NC", "postal_code": "28202", "going_count": null, "all_day": "0", "latitude": "35.2250606", "groups": null, "url": "http://charlotte.eventful.com/events/neil-diamond-/E0-001-098205170-1?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "E0-001-098205170-1", "privacy": "1", "city_name": "Charlotte", "link_count": null, "longitude": "-80.8393335", "country_name": "United States", "country_abbr": "USA", "region_name": "North Carolina", "start_time": "2017-04-28 20:00:00", "tz_id": null, "description": null, "modified": "2017-04-02 14:05:57", "venue_display": "1", "tz_country": null, "performers": { "performer": { "creator": "jordan", "linker": "evdb", "name": "Neil Diamond", "url": "http://concerts.eventful.com/Neil-Diamond?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000020959-4", "short_bio": "Rock" } }, "title": "Neil Diamond", "venue_address": "333 East Trade Street", "geocode_type": "EVDB Geocoder", "tz_olson_path": null, "recur_string": null, "calendars": null, "owner": "evdb", "going": null, "country_abbr2": "US", "categories": { "category": [{ "name": "Concerts &amp; Tour Dates", "id": "music" }] }, "image": { "small": { "width": "48", "url": "http://s1.evcdn.com/images/small/I0-001/004/274/032-9.jpeg_/neil-diamond-32.jpeg", "height": "48" }, "width": "48", "caption": null, "medium": { "width": "128", "url": "http://s1.evcdn.com/images/medium/I0-001/004/274/032-9.jpeg_/neil-diamond-32.jpeg", "height": "128" }, "url": "http://s1.evcdn.com/images/small/I0-001/004/274/032-9.jpeg_/neil-diamond-32.jpeg", "thumb": { "width": "48", "url": "http://s1.evcdn.com/images/thumb/I0-001/004/274/032-9.jpeg_/neil-diamond-32.jpeg", "height": "48" }, "height": "48" }, "created": "2016-11-30 11:59:00", "venue_id": "V0-001-001286706-3", "tz_city": null, "stop_time": null, "venue_name": "Spectrum Center (formerly Time Warner Cable Arena)", "venue_url": "http://charlotte.eventful.com/venues/spectrum-center-formerly-time-warner-cable-a-/V0-001-001286706-3?utm_source=apis&utm_medium=apim&utm_campaign=apic" },

//         { "watching_count": null, "olson_path": "America/New_York", "calendar_count": null, "comment_count": null, "region_abbr": "NC", "postal_code": "28202", "going_count": null, "all_day": "0", "latitude": "35.2250606", "groups": null, "url": "http://charlotte.eventful.com/events/chris-tomlin-/E0-001-097759568-1?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "E0-001-097759568-1", "privacy": "1", "city_name": "Charlotte", "link_count": null, "longitude": "-80.8393335", "country_name": "United States", "country_abbr": "USA", "region_name": "North Carolina", "start_time": "2017-04-13 19:00:00", "tz_id": null, "description": null, "modified": "2017-01-03 20:41:05", "venue_display": "1", "tz_country": null, "performers": { "performer": [{ "creator": "supermorgo", "linker": "evdb", "name": "Chris Tomlin", "url": "http://concerts.eventful.com/Chris-Tomlin?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000011114-7", "short_bio": "Christian worship leader / songwriter" }, { "creator": "wordmusic", "linker": "evdb", "name": "Big Daddy Weave", "url": "http://concerts.eventful.com/Big-Daddy-Weave?utm_source=apis&utm_medium=apim&utm_campaign=apic", "id": "P0-001-000026539-6", "short_bio": "Christian rock, with a swing sound" }] }, "title": "Chris Tomlin", "venue_address": "333 East Trade Street", "geocode_type": "EVDB Geocoder", "tz_olson_path": null, "recur_string": null, "calendars": null, "owner": "evdb", "going": null, "country_abbr2": "US", "categories": { "category": [{ "name": "Concerts &amp; Tour Dates", "id": "music" }] }, "image": { "small": { "width": "48", "url": "http://s3.evcdn.com/images/small/I0-001/000/205/742-7.jpg_/chris-tomlin-42.jpg", "height": "48" }, "width": "48", "caption": null, "medium": { "width": "128", "url": "http://s3.evcdn.com/images/medium/I0-001/000/205/742-7.jpg_/chris-tomlin-42.jpg", "height": "128" }, "url": "http://s3.evcdn.com/images/small/I0-001/000/205/742-7.jpg_/chris-tomlin-42.jpg", "thumb": { "width": "48", "url": "http://s3.evcdn.com/images/thumb/I0-001/000/205/742-7.jpg_/chris-tomlin-42.jpg", "height": "48" }, "height": "48" }, "created": "2016-11-11 21:08:28", "venue_id": "V0-001-001286706-3", "tz_city": null, "stop_time": null, "venue_name": "Spectrum Center (formerly Time Warner Cable Arena)", "venue_url": "http://charlotte.eventful.com/venues/spectrum-center-formerly-time-warner-cable-a-/V0-001-001286706-3?utm_source=apis&utm_medium=apim&utm_campaign=apic" }
//     ]
// }

//___________________________________________________
// Function to initialize the Mapping function. Provided by Google Maps API
function initMap(events) {

    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 9,
        center: { lat: parseFloat(events.event[0].latitude), lng: parseFloat(events.event[0].longitude) }
    }); // End of Javascript getElementById

    // Create a for loop to look into each of the objects and display lat and long
    // jlb-make the for loop check for and avoid duplicate venues
    // jlb-declare i with var to make local scope, avoid conflict with other js
    var location = [],
        venue_names = [];
    // events.forEach(function(venue) {
    for (var i0 = 0; i0 < events.event.length; i0++) {
        if (!venue_names.includes(events.event[i0].venue_name)){
            location.push([{ lat: parseFloat(events.event[i0].latitude), lng: parseFloat(events.event[i0].longitude) }, events.event[i0].venue_url, events.event[i0].venue_name]);
            venue_names.push(events.event[i0].venue_name);
            console.log(venue_names);
        }
    }
    // }); // End of for loop
    
    //For Loop to create a Marker for each corresponding index in the array
    var labelCounter = 0;
    console.log("location.length=", location.length);
    for (var i1 = 0; i1 < location.length; i1++) {
        if (labelCounter > 25){
            labelChar = "";
        } else {
            labelChar = String.fromCharCode(labelCounter + 65);
            labelCounter++;
        }
        var marker = new google.maps.Marker({
            position: location[i1][0],
            map: map,
            label: labelChar,
            url: location[i1][1],
            title: location[i1][2]
        });//End of marker

        google.maps.event.addListener(marker, 'click', function(){
            windowOpen(this.url)
        });

    }


} //End of initMap()
